export const mockedUsers = [
  {
    _id: 1,
    email: 'test1@email.com',
    password: 'password1',
    username: 'username1',
    name: 'name1',
    surname: 'surname1',
    avatar: 'https://example.com/photo.png',
    biography: 'biography1',
    posts: [],
    followers: [],
    following: [],
    favGames: [],
  },
  {
    _id: 2,
    email: 'test2@email.com',
    password: 'password2',
    username: 'username2',
    name: 'name2',
    surname: 'surname2',
    avatar: '',
    biography: 'biography2',
    posts: [],
    followers: [],
    following: [],
    favGames: [],
  },
];
